import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'
import '../styles/globals.css'


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <title>Live CSS</title>
      </Head>
      <div className="container">
        <NavContainer>
          <h3>LiveCSS</h3>
          <nav>
            <Link href="/">
              <a>Box Shadow</a>
            </Link>
          </nav>
        </NavContainer>
        <Component {...pageProps} />
      </div>
    </>
  )
}

const NavContainer = styled.div`
  height: 100px;
  display: flex;
  align-items: center;
  justify-content: space-between;

  h3 {
    font-size: 35px;
    font-weight: 400;
  }

  nav a {
    &:hover {
      text-decoration: underline;
    }
  }
`
export default MyApp
